server:
  port: 9000
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        # 默认数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/dax-pay?serverTimezone=GMT%2B8&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&nullCatalogMeansCurrent=true
          username: root
          password: root
    hikari:
      # 30 秒, 心跳检测
      keepalive-time: 30000
      # 300 分钟, 连接最大存活时间
      max-lifetime: 18000000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      cluster:
        refresh:
          # 自适应拓扑刷新
          adaptive: true
          # 群集拓扑刷新周期
          period: 60s
  # 如果不使用MQ的话, 可以将项目中 @EnableRabbit 给注释掉, 就不会一直报错了
  rabbitmq:
    # 虚拟主机
    virtual-host: dax-pay
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # 重试机制
        retry:
          enabled: true
          max-attempts: 5
  #静态资源加载配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
  thymeleaf:
    cache: false
  # 定时任务
  quartz:
    # 持久化方式
    job-store-type: jdbc
    #定时任务启动开关，true-开  false-关
    auto-startup: true
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
# 开发时显示debug日志
logging:
  level:
    cn.bootx.**: debug
    org.springframework.jdbc.core: debug
# 项目配置
bootx:
  common:
    # 接口文档
    swagger:
      enabled: true
      author: bootx
      version: 2.0.0
      title: 开源支付平台-单商户
      description: 开源支付平台-单商户版
      # 多模块扫码
      base-packages:
        "[支付网关API]": cn.bootx.platform.daxpay.gateway
        "[支付管理接口]": cn.bootx.platform.daxpay.admin
        "[BootxPlatform接口]":
          - cn.bootx.platform.common
          - cn.bootx.platform.starter
          - cn.bootx.platform.iam
          - cn.bootx.platform.baseapi
          - cn.bootx.platform.notice
    # 缓存
    cache:
      # 默认超时时间 30分钟
      default-ttl: 1800
      # 对Key设置超时间 (秒)
      keys-ttl:
        "[iam:user:path]" : 5200
        "[iam:ignore:path]" : 28800
        "[base:china:region]" : 28800
    # 序列生成器
    sequence:
      type: jdbc
    # 异常
    exception:
      # 显示详细异常
      show-full-message: true
  starter:
    # 认证
    auth:
      default-password: 123456
      ignore-urls:
        - '/actuator/**'
        - '/v3/api-docs/**'
        - '/doc.html'
        - '/swagger-resources/**'
        - '/token/**'
        - '/ws/**'
        - '/demo/**'
        - '/test/**'
        - '/webjars/**'
        - '/css/**'
        - '/error'
        - '/favicon.ico'
        - '/**'
    # 审计日志
    audit-log:
      # 审计日志存储
      store: jdbc
      # ip归属地
      ip2region:
        # 数据文件路径
        file-path: /data/ip2region/ip2region.xdb
        # 查询方式
        search-type: cache
    # 数据权限
    data-perm:
      #  需要符合AES密钥的要求
      field-decrypt-key: "UCrtxSCwYZNCIlav"
    # 文件上传
    file-upload:
      server-url: http://127.0.0.1:9000
# 自动建表
table-modify:
  update-type: update
  database-type: mysql
  fail-fast: true
  scan-package: cn.bootx.platform.daxpay
dromara:
  #文件存储配置,
  x-file-storage:
    #默认使用的存储平台
    default-platform: local
    #缩略图后缀，例如【.min.jpg】【.png】
    thumbnail-suffix: ".min.jpg"
    local-plus:
      # 不启用自带的访问映射, 使用自定义的访问实现
      # 存储平台标识
      - platform: local
        enableStorage: true
        # 文件存储路径
        storage-path: D:/data/files/
