version: '3'
services:
  platform:
    image: dax-start:latest
    restart: always
    ports:
      - "9898:9898"
    volumes:
      # 读取外部化配置文件(根据实际服务器环境做修改), 宿主机目录:容器目录
      - /data/logs/dax-start:/logs # 日志
      - /root/dax-pay/application-dev.yml:/application-dev.yml # 配置
      - /root/dax-pay/logback-spring.xml:/logback-spring.xml # 日志框架
